apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sprout
spec:
  replicas: 1
  selector:
    matchLabels:
      service: sprout
  template:
    metadata:
      labels:
        service: sprout
        snmp: enabled
    spec:
      containers:
      - image: "kubemaster.local:5000/clearwater/sprout:latest"
        imagePullPolicy: Always
        name: sprout
        lifecycle:
          postStart:
            exec:
             command: ["/bin/bash", "-c", "sleep 10; /etc/init.d/sprout restart"]
        ports:
        - containerPort: 22
        envFrom:
        - configMapRef:
              name: env-vars
        env:
        - name: ZONE
          value: default.svc.cluster.local
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        livenessProbe:
          exec:
            command: ["/bin/bash", "/usr/share/kubernetes/liveness.sh", "5052 5054"]
          initialDelaySeconds: 30
          periodSeconds: 3
        readinessProbe:
          exec:
            command: ["/bin/bash", "/usr/share/kubernetes/liveness.sh", "5052 5054"]
        volumeMounts:
        - name: sproutlogs
          mountPath: /var/log/sprout
      - image: busybox
        name: tailer
        command: [ "tail", "-F", "/var/log/sprout/sprout_current.txt" ]
        volumeMounts:
        - name: sproutlogs
          mountPath: /var/log/sprout
      volumes:
      - name: sproutlogs
        emptyDir: {}
      imagePullSecrets:
      - name: ~
      restartPolicy: Always
